spring:
  redis:
    pool:
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 10
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 10
      # 连接池中的最小空闲连接
      min-idle: 0
      # 连接超时时间（毫秒）
      timeout: 20000
    cluster:
      max-redirects: 3
      nodes: 192.168.179.129:7001,192.168.179.129:7002,192.168.179.129:7003

server:
  port: 8080
